version: '2'

services:
  db:
    image: postgres
  redis:
    image: redis
  web:
    env_file:
      - web-variables.env
    image: filav
    restart: on-failure
    ports:
      - "14430:443"
    volumes:
      - ./crt:/crt:ro
    links:
      - db:db
      - redis:redis
