# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Filas',
                'verbose_name': 'Fila',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estado', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Em pausa'), (2, 'Esperando cliente'), (3, 'Atendendo')], default=0)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postos', to='fila.Fila', verbose_name='Fila')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
            ],
            options={
                'verbose_name_plural': 'Postos',
                'verbose_name': 'Posto',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('estado', models.IntegerField(choices=[(0, 'Inicial'), (1, 'Na Fila'), (2, 'Cancelado'), (3, 'No Atendimento'), (4, 'Ausente'), (5, 'Atendido')], default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='fila.Fila', verbose_name='Fila')),
            ],
        ),
        migrations.AddField(
            model_name='posto',
            name='turno_em_atencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fila.Turno', verbose_name='Turno em atencao'),
        ),
        migrations.AddField(
            model_name='fila',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filas', to='fila.Local', verbose_name='Local'),
        ),
        migrations.AlterUniqueTogether(
            name='fila',
            unique_together=set([('local', 'nome')]),
        ),
    ]
