# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fila.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fila', '0002_auto_20171109_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(default=fila.models.gerar_codigo_qr, max_length=100, verbose_name='Codigo QR')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='posto',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Em pausa'), (2, 'Esperando cliente'), (3, 'Cliente chamado'), (4, 'Atendendo')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='posto',
            name='funcionario',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='fila.Funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='posto',
            name='turno_em_atencao',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='fila.Turno', verbose_name='Turno em atencao'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inicial'), (1, 'Na Fila'), (2, 'Cancelado'), (4, 'No Atendimento'), (5, 'Ausente'), (6, 'Atendido')], default=1),
        ),
    ]
