# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0004_qrcode_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'permissions': (('habilitar_scanner', 'Pode habilitar scanners de codigos QR para acessar a fila virtual.'),)},
        ),
    ]
