# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0005_auto_20171229_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='turno_em_atencao',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='fila.Turno', verbose_name='Turno em atencao'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inicial'), (1, 'Na Fila'), (2, 'Cancelado'), (3, 'Ir no posto'), (4, 'No Atendimento'), (5, 'Ausente'), (6, 'Atendido')], default=1),
        ),
    ]
