# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0006_auto_20171229_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postos', to='fila.Local', verbose_name='Local'),
        ),
    ]
