# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0008_auto_20180102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inativo'), (1, 'Em pausa'), (2, 'Esperando cliente'), (3, 'Cliente chamado'), (4, 'Atendendo')], default=0),
        ),
        migrations.AlterField(
            model_name='posto',
            name='turno_em_atencao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fila.Turno', verbose_name='Turno em atencao'),
        ),
    ]
