# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0011_telegram_telegramdispatcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramDispatcher',
        ),
    ]
