# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0014_turno_turno_finalizado_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='turno_finalizado_date',
            new_name='fim_espera_date',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='cliente_chamado_date',
            new_name='inicio_espera_date',
        ),
    ]
