# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0015_auto_20180216_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='media_espera',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fila',
            name='n_espera',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
