# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0016_auto_20180219_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fila',
            name='n_espera',
        ),
    ]
