# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0017_remove_fila_n_espera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='media_espera',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo de atendimento medio (segundos)'),
        ),
    ]
